theme: jekyll-theme-midnight
title: Showcases in Mathematical Physics
description: Notes, discussions, everything about Mathematical Physics.
github:
  is_project_page: false
future: true
timezone: America/Sao_Paulo
baseurl: "/teste"
collections:
  seminars:
    output: true
  suggestions:
    output: false
  bibliography:
    output: false
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "seminars"
    values:
      layout: "seminar"
