theme: jekyll-theme-midnight
title: Showcases in Mathematical Physics
description: Notes, discussions, everything about Mathematical Physics.
github:
  is_project_page: false
future: true
timezone: America/Sao_Paulo
baseurl: "/teste"
url: "https://alexandre-joao.github.io"
collections:
  seminars:
    output: true
  suggestions:
    output: false
  bibliography:
    output: false
  notes:
    output: true 
    permalink: /notes/:path/
  Discussions:
    output: true 
    permalink: /Discussions/:path/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "seminars"
    values:
      layout: "seminar"
